<a href="https://colab.research.google.com/github/YuseokYang/Study-Everyday/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [8]:
arr = np.array([[1,2,3],[4,5,6]])
arr.shape

(2, 3)

In [7]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]]])
arr.shape

(3, 3, 3)

In [9]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
a = np.full((3,3),1.5)
a

array([[1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5]])

In [18]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
a = np.tri(3)
a

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [20]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
a = np.linspace(0,10,5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
a = np.logspace(1,2,5)
a

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [27]:
a = np.random.random()
a

0.7494037071180638

In [30]:
a = np.random.random((4,4))
a

array([[0.069843  , 0.93634015, 0.48088393, 0.12627999],
       [0.47802493, 0.56423231, 0.83183232, 0.69328533],
       [0.12020077, 0.04531466, 0.23140206, 0.55731441],
       [0.0711439 , 0.74798792, 0.56072259, 0.11059976]])

In [33]:
a = np.random.randint(1,10)
a

6

In [40]:
a = np.random.randint(10,100, (4,4))
a

array([[98, 79, 49, 18],
       [39, 54, 93, 55],
       [58, 85, 53, 20],
       [37, 24, 53, 67]])

In [41]:
a = np.random.rand(3,3)
a

array([[0.70495931, 0.21453003, 0.39387183],
       [0.43674678, 0.01685464, 0.2423514 ],
       [0.09289387, 0.02485619, 0.5260198 ]])

In [42]:
a = np.random.randn(3,3)
a

array([[ 1.27815528,  1.80630099,  0.99312328],
       [-0.30908371, -0.171085  , -1.04892656],
       [-0.38195549,  1.61193245,  0.84598042]])

In [43]:
arr = np.arange(1,6)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)

[1 2 3 4 5]
1
(5,)
int64
5
8
40


In [44]:
a = np.arange(10)
print(a)
print(a[0])
print(a[-1])
print(a[0:5])
a[0] = 10
print(a)

[0 1 2 3 4 5 6 7 8 9]
0
9
[0 1 2 3 4]
[10  1  2  3  4  5  6  7  8  9]


In [50]:
a = np.arange(1,10).reshape(3,3)
print(a)
a[1,1]=1000
a

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[   1,    2,    3],
       [   4, 1000,    6],
       [   7,    8,    9]])

In [57]:
a=np.arange(25).reshape(5,5)
print(a)
a[::-1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [59]:
a = np.arange(1,6)
print(a)
b = [True,False,True,False,True]
a[b]

[1 2 3 4 5]


array([1, 3, 5])

In [65]:
a = np.arange(1,10)
print(a)
even = a%2 ==0
a[even]

[1 2 3 4 5 6 7 8 9]


array([2, 4, 6, 8])

In [68]:
mask = (a > 5) & (a < 11)
a[mask]

array([6, 7, 8, 9])

In [70]:
a[~(a%2==0)]

array([1, 3, 5, 7, 9])

In [72]:
a = np.arange(1,11)
b = np.arange(1,11)
np.add(a,b)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [73]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [74]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [75]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [76]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [77]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
b = a.sum(axis=0)
b

array([12, 15, 18])

In [79]:
b = a.sum(axis=1)
b

array([ 6, 15, 24])

In [80]:
a.max()

9

In [81]:
a.max(axis=0)

array([7, 8, 9])

In [82]:
a.max(axis=1)

array([3, 6, 9])

In [83]:
a.mean(axis=0)

array([4., 5., 6.])

In [87]:
np.median(a, axis=1)

array([2., 5., 8.])

In [88]:
a = np.array([1,2,3,4,5])
b = 1
a+b

array([2, 3, 4, 5, 6])

In [89]:
a=np.arange(1,25).reshape(4,6)
a+100

array([[101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112],
       [113, 114, 115, 116, 117, 118],
       [119, 120, 121, 122, 123, 124]])

In [91]:
new_arr = np.full_like(a,100)
a+new_arr

array([[101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112],
       [113, 114, 115, 116, 117, 118],
       [119, 120, 121, 122, 123, 124]])

In [94]:
a = np.arange(5).reshape(1,5)
b = np.arange(5).reshape(5,1)
print(a)
print(b)
a+b

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]


array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [98]:
import time
a = range(100000)
sum=0
start = time.time()
for i in a:
  sum+=i
end=time.time()
print(end-start)

0.022391080856323242


In [99]:
a = np.arange(1,100001)
start = time.time()
a.sum()
end = time.time()
print(end-start)

0.00031495094299316406


In [106]:
a = np.random.randint(1,10,(3,3))
print(a)
print(a.T)

[[5 7 6]
 [7 5 8]
 [3 8 1]]
[[5 7 3]
 [7 5 8]
 [6 8 1]]


In [116]:
a = np.array([[1,2,3],[4,5,6]])
a.ravel()
b = a.ravel()
b[0] = 10
a

array([[10,  2,  3],
       [ 4,  5,  6]])

In [119]:
x = np.arange(20)
y = x.reshape(4,5)
y[0] = 1000
x

array([1000, 1000, 1000, 1000, 1000,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])