<a href="https://colab.research.google.com/github/YuseokYang/Study-Everyday/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                [[10,11,12],[13,14,15],[16,17,18]],
                [[19,20,21],[22,23,24],[25,26,27]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr = np.empty((3,3))
arr

array([[4.83966812e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
arr = np.full((2,4), np.e)
arr

array([[2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183]])

In [ ]:
a = np.eye(2)
a

array([[1., 0.],
       [0., 1.]])

In [ ]:
arr = np.tri(5)
arr

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr = np.linspace(-10,10, 10)
arr

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
arr = np.logspace(np.log10(10), np.log10(100), 5)
arr

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [ ]:
a = np.random.random()
a

0.05954662451900328

In [ ]:
a = np.random.random((3,3))
a

array([[0.15787683, 0.89876674, 0.60461509],
       [0.42102268, 0.76605495, 0.81344848],
       [0.92847045, 0.86088113, 0.83008727]])

In [ ]:
a = np.random.randint(10, size=(4,4))
a

array([[4, 8, 0, 8],
       [2, 9, 0, 6],
       [5, 1, 5, 1],
       [8, 8, 8, 4]])

In [ ]:
a = np.random.uniform(0,1, size=(4,4)).round(2)
a

array([[0.54, 0.34, 0.  , 0.82],
       [0.33, 0.22, 0.31, 0.07],
       [0.87, 0.22, 0.17, 0.74],
       [0.85, 0.22, 0.25, 0.12]])

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1 = np.arange(10)
print(a1[0])
print(a1[-1])

0
9


In [ ]:
a2 = np.arange(9).reshape((3,3))
print(a2)
a2[1,2] #이게 한 번만 접근해서 더 좋다

[[0 1 2]
 [3 4 5]
 [6 7 8]]


5

In [ ]:
a1 = np.arange(24).reshape((4,6))
print(a1)

a2 = np.arange(10)
print(a2)
a2[::-1]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[0 1 2 3 4 5 6 7 8 9]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
a1[:,::-1]

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18]])

In [ ]:
bool_array = np.random.randint(0,2, size=(5,)).astype(bool)
a = np.arange(5)
a[bool_array]

array([1, 2, 3])

In [ ]:
a = np.arange(10)
print(a % 2 == 1)
a[a%2==1]

[False  True False  True False  True False  True False  True]


array([1, 3, 5, 7, 9])

In [ ]:
(a>5) | (a<2)

array([ True,  True, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
a = np.arange(1,11)
b = np.arange(1,11)
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.floor_divide(a,b))

[0 0 0 0 0 0 0 0 0 0]
[  1   4   9  16  25  36  49  64  81 100]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]


In [ ]:
a = np.arange(1,11)
print(np.exp(a))
print(np.log(a))

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [ ]:
a = np.arange(1,10).reshape((3,3))
print(a)
print(np.sum(a,axis=0) )
print(np.sum(a, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


In [ ]:
a = np.arange(1,10).reshape((3,3))
print(a)
print(a.max(axis=0))
a.max(axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]


array([3, 6, 9])

In [ ]:
print(f'{a.min(axis=0) = }')
print(f'{a.min(axis=1) = }')

a.min(axis=0) = array([1, 2, 3])
a.min(axis=1) = array([1, 4, 7])


In [6]:
a = np.arange(1,10).reshape((3,3))
print(a)
print(a.mean(axis=0))
print(np.mean(a, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4. 5. 6.]
[2. 5. 8.]


In [7]:
a = np.arange(1,10).reshape((3,3))
print(a.std(axis=0))
print(np.std(a, axis=1))

[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


In [8]:
a = np.arange(1,10)
a + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
a = np.arange(1,25).reshape((4,6))
a + 10

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34]])

In [13]:
arr = np.full((3,3), 10)
arr

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [16]:
a = np.arange(5).reshape((1,5))
b = np.arange(5).reshape((5,1))
print(a)
print()
print(b)
print()
print(a+b)

[[0 1 2 3 4]]

[[0]
 [1]
 [2]
 [3]
 [4]]

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [17]:
import time
a = np.arange(1000000)
result = 0
t_start = time.time()
for i in a:
  result += i
t_end = time.time()
print(f'{result = }\t {t_end - t_start = }')


result = 499999500000	 t_end - t_start = 0.27004051208496094


In [23]:
a = np.arange(1000000)
t_start = time.time()
result = a.sum()
t_end = time.time()
print(f'{result = }\t {t_end - t_start = }')

result = 499999500000	 t_end - t_start = 0.0010607242584228516


In [26]:
a = np.random.randint(1,10, size=(3,3))
print(a)
print()
print(a.T)

[[8 7 8]
 [3 5 1]
 [9 1 1]]

[[8 3 9]
 [7 5 1]
 [8 1 1]]


In [28]:
a = np.arange(12).reshape((3,4))
print(a)
print()
b = a.ravel()
b[0] = 10
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[10  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
a = np.arange(12).reshape((3,4))
print(a)
print()
b = a.ravel()
b[0] =1000
print(b)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[1000    1    2    3    4    5    6    7    8    9   10   11]
[[1000    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]


In [40]:
x = np.arange(20)
print(np.resize(x, (3,5)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [43]:
a = np.arange(3)
b = np.append(a,3)
b

array([0, 1, 2, 3])

In [49]:
a = np.arange(6).reshape((2,3))
b = np.arange(3).reshape((1,3))
print(a,b, sep='\n')
print()
print(np.append(a,b))

[[0 1 2]
 [3 4 5]]
[[0 1 2]]

[0 1 2 3 4 5 0 1 2]


In [50]:
a = np.arange(3).reshape((3,))
b = np.insert(a,1,5)

array([0, 1, 2])

[1, 10000, 2, 3]

In [54]:
a = np.array([[1,1],[2,2],[3,3]])
b = np.insert(a,1,5,axis=0)
b

array([[1, 1],
       [5, 5],
       [2, 2],
       [3, 3]])

In [56]:
a = np.arange(12).reshape((3,4))
print(a)
print()
print(np.delete(a,1,axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 8  9 10 11]]
